language: node_js

services:
  - xvfb

branches:
  only:
  - master
  - /^release\/.*$/

stages:
  - test
  - release-rc
  - release-docker
  - test-external

node_js:
  - 'lts/*'
  - 'node'

os:
  - linux
  - osx
  - windows

env:
  # This stops Windows builds from hanging
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
  - YARN_GPG=no

addons:
  apt:
    packages:
      # Fixes error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
      # https://github.com/electron/electron/issues/1518
      - libgconf-2-4
      # Ensure chrome is the latest version
      # https://stackoverflow.com/questions/57903415/travis-ci-chrome-62-instead-of-77
      - dpkg
  chrome: stable
  firefox: latest

before_install:
  # prevents windows error: npm ERR! ... git-sh-setup: file not found
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH=/c/PROGRA~1/Git/usr/bin:/c/PROGRA~1/Git/mingw64/libexec/git-core:$PATH ; fi
  # upgrading npm on travis/windows/node 14 is completely broken
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export NODE_INSTALL_DIR=`npm prefix -g` ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then mv $NODE_INSTALL_DIR/node_modules $NODE_INSTALL_DIR/node_modules_old ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then mkdir $NODE_INSTALL_DIR/node_modules ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then rm -f $NODE_INSTALL_DIR/npm $NODE_INSTALL_DIR/npm.cmd $NODE_INSTALL_DIR/npm.ps1 $NODE_INSTALL_DIR/npx $NODE_INSTALL_DIR/npx.cmd $NODE_INSTALL_DIR/npx.ps1 ; fi
  # workspaces require npm 7 or above
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then node $NODE_INSTALL_DIR/node_modules_old/npm/bin/npm-cli.js i -g npm@latest ; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then npm install -g npm@latest ; fi
  # allow windows to run scripts with node 14 and npm 7 (may not be necessary when node 14 is no longer lts)
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm config set script-shell c:/PROGRA~1/Git/bin/bash.exe ; fi
  # only run jobs in packages that have changed since master in PR builds
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export RUN_SINCE='--since master' ; fi
  # modules with pre-built binaries may not have deployed versions for bleeding-edge node so this lets us fall back to building from source
  - npm install -g node-pre-gyp

script:
  - npm run test:node -- $RUN_SINCE -- -- --timeout 10000 --bail

jobs:
  allow_failures:
    - name: external - ipfs-webui
    - name: external - ipfs-companion
    - name: external - npm-on-ipfs
    - name: external - peer-base
    - name: external - service-worker-gateway
    - name: external - orbit-db
    - name: external - ipfs-log
    - name: external - sidetree

  include:
    - stage: test
      name: lint
      node_js: 'node'
      script:
        - npm run lint -- $RUN_SINCE --concurrency 1

    - stage: test
      name: dep-check (production deps)
      node_js: 'node'
      script:
        - npm run dep-check -- $RUN_SINCE -- -- -p

    - stage: test
      name: dep-check (unused deps)
      node_js: 'node'
      script:
        - npm run dep-check -- $RUN_SINCE -- -- -- --unused

    - stage: test
      name: chrome
      node_js: 'node'
      script:
        - npm run test:browser -- $RUN_SINCE -- -- --bail

    - stage: test
      name: chrome webworker
      node_js: 'node'
      script:
        - npm run test:webworker -- $RUN_SINCE -- -- --bail --timeout 60000

    - stage: test
      name: firefox
      node_js: 'node'
      script:
        - npm run test:browser -- $RUN_SINCE -- -- --bail --browsers FirefoxHeadless

    - stage: test
      name: firefox webworker
      node_js: 'node'
      script:
        - npm run test:webworker -- $RUN_SINCE -- -- --bail --browsers FirefoxHeadless --timeout 60000

    - stage: test
      name: electron-main
      node_js: 'node'
      script:
        - npm run test:electron-main -- $RUN_SINCE -- -- --bail --timeout 60000

    - stage: test
      name: electron-renderer
      node_js: 'node'
      script:
        - npm run test:electron-renderer -- $RUN_SINCE -- -- --bail --timeout 60000

    - stage: test
      name: interop - node
      node_js: 'node'
      script:
        - npm run test:interop -- $RUN_SINCE -- -- -- -t node --bail

    - stage: test
      name: interop - browser
      node_js: 'node'
      script:
        - npm run test:interop -- $RUN_SINCE -- -- -- -t browser --bail

    - stage: test
      name: interop - electron-main
      node_js: 'node'
      script:
        - npm run test:interop -- $RUN_SINCE -- -- -- -t electron-main -f ./test/node.js --bail --timeout 60000

    - stage: test
      name: interop - electron-renderer
      node_js: 'node'
      script:
        - npm run test:interop -- $RUN_SINCE -- -- -- -t electron-renderer -f ./test/browser.js -bail --timeout 60000

    - stage: test
      name: js-ipfs interface tests - node
      node_js: 'node'
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t node

    - stage: test
      name: js-ipfs interface tests - chrome
      node_js: 'node'
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t browser

    - stage: test
      name: js-ipfs interface tests - chrome webworker
      node_js: 'node'
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t webworker --timeout 60000

    - stage: test
      name: js-ipfs interface tests - firefox
      node_js: 'node'
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t browser --browsers FirefoxHeadless

    - stage: test
      name: js-ipfs interface tests - firefox webworker
      node_js: 'node'
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t webworker --browsers FirefoxHeadless --timeout 60000

    - stage: test
      name: js-ipfs interface tests - electron main
      node_js: 'node'
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t electron-main --timeout 60000

    - stage: test
      name: js-ipfs interface tests - electron renderer
      node_js: 'node'
      script:
        - npm run test:interface:core -- $RUN_SINCE -- -- --bail -t electron-renderer --timeout 60000

    - stage: test
      name: js-ipfs interface tests - ipfs-client - node
      node_js: 'node'
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t node

    - stage: test
      name: js-ipfs interface tests - ipfs-client - chrome
      node_js: 'node'
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t browser

    - stage: test
      name: js-ipfs interface tests - ipfs-client - chrome webworker
      node_js: 'node'
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t webworker --timeout 60000

    - stage: test
      name: js-ipfs interface tests - ipfs-client - firefox
      node_js: 'node'
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t browser --browsers FirefoxHeadless

    - stage: test
      name: js-ipfs interface tests - ipfs-client - firefox webworker
      node_js: 'node'
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t webworker --browsers FirefoxHeadless --timeout 60000

    - stage: test
      name: js-ipfs interface tests - ipfs-client - electron main
      node_js: 'node'
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t electron-main --timeout 60000

    - stage: test
      name: js-ipfs interface tests - ipfs-client - electron renderer
      node_js: 'node'
      script:
        - npm run test:interface:client -- $RUN_SINCE -- -- --bail -t electron-renderer --timeout 60000

    - stage: test
      name: http-api-client interface tests vs go-ipfs - node
      node_js: 'node'
      script:
        - npm run test:interface:http-go -- $RUN_SINCE -- -- --bail -t node

    - stage: test
      name: http-api-client interface tests vs go-ipfs - chrome
      node_js: 'node'
      script:
        - npm run test:interface:http-go -- $RUN_SINCE -- -- --bail -t browser

    - stage: test
      name: http-api-client interface tests vs go-ipfs - chrome webworker
      node_js: 'node'
      script:
        - npm run test:interface:http-go -- $RUN_SINCE -- -- --bail -t webworker --timeout 60000

    - stage: test
      name: http-api-client interface tests vs go-ipfs - firefox
      node_js: 'node'
      script:
        - npm run test:interface:http-go -- $RUN_SINCE -- -- --bail -t browser --browsers FirefoxHeadless

    - stage: test
      name: http-api-client interface tests vs go-ipfs - firefox webworker
      node_js: 'node'
      script:
        - npm run test:interface:http-go -- $RUN_SINCE -- -- --bail -t webworker --browsers FirefoxHeadless --timeout 60000

    - stage: test
      name: http-api-client interface tests vs js-ipfs - node
      node_js: 'node'
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t node

    - stage: test
      name: http-api-client interface tests vs js-ipfs - chrome
      node_js: 'node'
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t browser

    - stage: test
      name: http-api-client interface tests vs js-ipfs - chrome webworker
      node_js: 'node'
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t webworker --timeout 60000

    - stage: test
      name: http-api-client interface tests vs js-ipfs - firefox
      node_js: 'node'
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t browser --browsers FirefoxHeadless

    - stage: test
      name: http-api-client interface tests vs js-ipfs - firefox webworker
      node_js: 'node'
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t webworker --browsers FirefoxHeadless --timeout 60000

    - stage: test
      name: http-api-client interface tests vs js-ipfs - electron main
      node_js: 'node'
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t electron-main --timeout 60000

    - stage: test
      name: http-api-client interface tests vs js-ipfs - electron renderer
      node_js: 'node'
      script:
        - npm run test:interface:http-js -- $RUN_SINCE -- -- --bail -t electron-renderer --timeout 60000

    - stage: test
      name: ipfs-message-port-client interface tests - chrome
      node_js: 'node'
      script:
        - npm run test:interface:message-port-client -- $RUN_SINCE -- -- --bail -t browser

    - stage: test
      name: ipfs-message-port-client interface tests - firefox
      node_js: 'node'
      script:
        - npm run test:interface:message-port-client -- $RUN_SINCE -- -- --bail -t browser --browsers FirefoxHeadless

    - stage: test
      name: examples
      node_js: 'node'
      install:
        - npm run configure-examples:add-examples-lerna
        - npm run configure-examples:add-examples-npm
        - npm install
        - npm run build
      script: npm run test -- --scope=example* --concurrency=1

    - stage: release-rc
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: release rc
      node_js: 'node'
      script:
        # travis does not fetch the whole repo history, but we need that to work out the
        # ref count to publish canary releases properly
        - git fetch --unshallow
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # only run if the last commit was not part of a release
        - if [[ ! `git log -n 1 -q` =~ publish ]]; then npm run release:rc ; fi

    - stage: release-docker
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: release docker
      node_js: 'node'
      script:
        # travis does not fetch the whole repo history, but we need that to work out the
        # ref count to publish canary releases properly
        - git fetch --unshallow
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # only run if the last commit was not part of a release
        - if [[ ! `git log -n 1 -q` =~ publish ]]; then npm run docker:rc ; fi

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - ipfs-webui
      node_js: 'node'
      script:
        - E2E_IPFSD_TYPE=js npm run test:external -- -- -- https://github.com/ipfs-shipyard/ipfs-webui.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - ipfs-companion
      node_js: 'node'
      script:
        - npm run test:external -- -- -- https://github.com/ipfs-shipyard/ipfs-companion.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - npm-on-ipfs
      node_js: 'node'
      script:
        - npm run test:external -- -- -- https://github.com/ipfs-shipyard/npm-on-ipfs.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - peer-base
      node_js: 'node'
      script:
        - npm run test:external -- -- -- https://github.com/achingbrain/peer-base.git --branch upgrade-to-latest-ipfs-rc --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - service-worker-gateway
      node_js: 'node'
      script:
        - npm run test:external -- -- -- https://github.com/ipfs-shipyard/service-worker-gateway.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - orbit-db
      node_js: 'node'
      script:
        - npm run test:external -- -- -- https://github.com/orbitdb/orbit-db.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - ipfs-log
      node_js: 'node'
      script:
        - npm run test:external -- -- -- https://github.com/orbitdb/ipfs-log.git --deps=ipfs@next

    - stage: test-external
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: external - sidetree
      node_js: 'node'
      script:
        - npm run test:external -- -- -- https://github.com/decentralized-identity/sidetree.git --deps=ipfs@next

notifications:
  email: false
